# This configuration file is an example of a basic predicting configuration
# Fill all keys before using it in a HoNCAML pipeline
# Keys which need values are the ones with a commend above

global:
  # Specify one of the following: [regression, classification]
  problem_type:

steps:
  data:
    extract:
      # Specify path of file containing input data
      filepath:

  model:
    extract:
      # Specify path in which model object is stored
      filepath:
    transform:
      predict:
        # Specify folder in which to store predictions
        path:
